---
id: klutz
name: Klutz
full: Comic reader application
description: Klutz is a Horde comics-fetching module.
list: horde
type: application
homepage: https://www.horde.org/apps/klutz
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^5.3
